### PR TITLE
Checkneedfor-recalc

### PR DESCRIPTION
**Pull request by EvenSol**

### CODE REVIEW

**Comment by asmfstatoil** [comment]
What is the difference between solved (property of processequipmentbaseclass) and isupdated?

**Comment by asmfstatoil** [comment]
There is probably a need for the functionality, I would just like to consider if the existing property for solved can be used.

**Comment by EvenSol** [comment]
> There is probably a need for the functionality, I would just like to consider if the existing property for solved can be used instead of creating a new property and new getter.

Yes, that is propabaly a good idea. Will look into that.

**Comment by EvenSol** [comment]
> There is probably a need for the functionality, I would just like to consider if the existing property for solved can be used instead of creating a new property and new getter.

updated to use solved

**Pull request merged**
