### PR TITLE
adedd javadoc template where missing

### PR DESCRIPTION
**Pull request by asmfstatoil**

### CODE REVIEW

**Comment by asmfstatoil** [comment]
@EvenSol can writing the missing documentation here be a nice task for Sviatoslav to familiarize him with the codebase?

**Review by EvenSol — APPROVED** [review]
Nice👍

**Comment by EvenSol** [comment]
@asmfstatoil I think @Sviatose would need some tips about the tools used to identify missing javadoc in visual studio code. I showed him :
https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html

But I guess you use automatic tools in visual studio code to detect this?

**Comment by asmfstatoil** [comment]
https://marketplace.visualstudio.com/items?itemName=madhavd1.javadoc-tools

**Pull request closed without merging**
