### PR TITLE
feat:nmVOCFlowRateAdded

### PR DESCRIPTION
**Pull request by Sviatose**
A method to get nmVOCFlowRate, also added units tonnes/year for component flow rate.

### CODE REVIEW

**Comment by EvenSol** [comment]
Great. We can discuss if this should be implemented as a transmitter for a stream.

**Comment by EvenSol** [comment]
Consider to remove the method from the ThermoSystem class (it could be that [NMVOCAnalyser](https://github.com/equinor/neqsim/pull/617/commits/c3e4c0bdefac885c9a0d6de6ceb484394797a204) is enough.

**Review by EvenSol — APPROVED** [review]

**Comment by Sviatose** [comment]
Yes, I will do that

**Comment by EvenSol** [comment]
is it ok I merge it into master, and that you update later?

**Pull request merged**
